### ISSUE TITLE
Failing integration tests: screenshot contains differences

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-confirm-dialog-flow#100]
There are 4 integration tests that are failing:

```
[ERROR] Tests run: 16, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 416.892 s <<< FAILURE! - in com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT
[ERROR] testReminderDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 36.426 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleConfirmDialogopened contains differences

[ERROR] testConfirmDeleteDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 15.794 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleConfirmDeleteDialogopened contains differences

[ERROR] testAreYouSureYouWantToPublishDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 36.184 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleConfirmPublishDialogopened contains differences

[ERROR] testUnsavedChangesDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 47.118 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleUnsavedChangesDialogopened contains differences
```

<details>
<summary>Full log</summary>
  <pre>
  <code>
[ERROR] Tests run: 16, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 416.892 s <<< FAILURE! - in com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT
[ERROR] testReminderDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 36.426 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleConfirmDialogopened contains differences
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.vaadin.flow.component.confirmdialog.test.AbstractParallelTest.compareScreen(AbstractParallelTest.java:35)
	at com.vaadin.flow.component.confirmdialog.test.helpers.Actionwords.iCompareTheDialogToReferenceImage(Actionwords.java:51)
	at com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT.testReminderDialog(FeaturesDiyIT.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at com.vaadin.testbench.parallel.ParallelScheduler$1.call(ParallelScheduler.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] testConfirmDeleteDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 15.794 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleConfirmDeleteDialogopened contains differences
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.vaadin.flow.component.confirmdialog.test.AbstractParallelTest.compareScreen(AbstractParallelTest.java:35)
	at com.vaadin.flow.component.confirmdialog.test.helpers.Actionwords.iCompareTheDialogToReferenceImage(Actionwords.java:51)
	at com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT.testConfirmDeleteDialog(FeaturesDiyIT.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at com.vaadin.testbench.parallel.ParallelScheduler$1.call(ParallelScheduler.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] testAreYouSureYouWantToPublishDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 36.184 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleConfirmPublishDialogopened contains differences
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.vaadin.flow.component.confirmdialog.test.AbstractParallelTest.compareScreen(AbstractParallelTest.java:35)
	at com.vaadin.flow.component.confirmdialog.test.helpers.Actionwords.iCompareTheDialogToReferenceImage(Actionwords.java:51)
	at com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT.testAreYouSureYouWantToPublishDialog(FeaturesDiyIT.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at com.vaadin.testbench.parallel.ParallelScheduler$1.call(ParallelScheduler.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] testUnsavedChangesDialog[ANY_Firefox_](com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT)  Time elapsed: 47.118 s  <<< FAILURE!
java.lang.AssertionError: Screenshot FeaturesDiy_SampleUnsavedChangesDialogopened contains differences
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.vaadin.flow.component.confirmdialog.test.AbstractParallelTest.compareScreen(AbstractParallelTest.java:35)
	at com.vaadin.flow.component.confirmdialog.test.helpers.Actionwords.iCompareTheDialogToReferenceImage(Actionwords.java:51)
	at com.vaadin.flow.component.confirmdialog.test.FeaturesDiyIT.testUnsavedChangesDialog(FeaturesDiyIT.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at com.vaadin.testbench.parallel.ParallelScheduler$1.call(ParallelScheduler.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
  </code>
  </pre>
</details>

See https://travis-ci.org/vaadin/vaadin-confirm-dialog-flow/jobs/608739619

**Comment by web-padawan** [comment]
This is fixed now.
